# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [46]:
# Numpy is a module from Python, we can import directly:

import numpy as np

#### 2. Print your NumPy version.

In [47]:
# If we want to know the version, we need to use np.version.version

print(np.version.version)

1.17.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [48]:
# Method 1: np.array and add all elements, with random module.
import random
a = np.array([[[random.randint(0,10), random.randint(0,10), random.randint(0,10), random.randint(0,10), random.randint(0,10)],[random.randint(0,10), random.randint(0,10), random.randint(0,10), random.randint(0,10), random.randint(0,10)],[random.randint(0,10), random.randint(0,10), random.randint(0,10), random.randint(0,10), random.randint(0,10)]],[[random.randint(0,10), random.randint(0,10), random.randint(0,10), random.randint(0,10), random.randint(0,10)],[random.randint(0,10), random.randint(0,10), random.randint(0,10), random.randint(0,10), random.randint(0,10)],[random.randint(0,10), random.randint(0,10), random.randint(0,10), random.randint(0,10), random.randint(0,10)]]])

a.shape

(2, 3, 5)

In [28]:
# Method 2: using np.random.randint
a2 = np.random.randint(10, size=(2, 3, 5))

a2.shape

(2, 3, 5)

In [49]:
# Method 3: We can use the module full_like to copy the shape of an existing array. In this way, we pick the array a2 and create one equal shape, but with all elements as a random number. That means we won't have all random numbers, but one random number in all positions.

a3 = np.full_like(a2, random.randint(0,10))
a3.shape

(2, 3, 5)

#### 4. Print *a*.


In [50]:
# your code here
print(a)
print(a2)
print(a3)

[[[ 2  2  5  7  3]
  [ 5  1  3 10  5]
  [ 5  9  8  4  1]]

 [[ 8  4  0  6  3]
  [ 7  7  3  2  3]
  [ 1  1  9  7  9]]]
[[[0 9 2 7 6]
  [0 9 2 2 7]
  [1 1 5 3 8]]

 [[7 2 3 2 8]
  [7 0 8 9 7]
  [7 3 0 0 5]]]
[[[6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]]

 [[6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [51]:
# Following the case on a3, we make a full_like array as 'a', but we set all values to 1 and after that, the T is transposing our array. From shape [2,3,5] to shape [5,3,2]

b = np.full_like(a, 1).T
b.shape

(5, 3, 2)

#### 6. Print *b*.


In [52]:
# your code here
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [53]:
# Both arrays have the same size. We can compare them:

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [57]:
# Both arrays have the same size, but they can't be added because of the different shapes.
# if we try 'c = a + b', it returns a ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [54]:
# your code here
c = b.T

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [55]:
# As now both arrays have the same shape, they can be added. Same shape means same values for each dimension, so we can add individually all the elements of each dimension.

d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [56]:
# As the array 'b' was built with all its elements equal to 1, all the elements from 'd' are elements from 'a' + 1
print(a)
print(d)

[[[ 2  2  5  7  3]
  [ 5  1  3 10  5]
  [ 5  9  8  4  1]]

 [[ 8  4  0  6  3]
  [ 7  7  3  2  3]
  [ 1  1  9  7  9]]]
[[[ 3  3  6  8  4]
  [ 6  2  4 11  6]
  [ 6 10  9  5  2]]

 [[ 9  5  1  7  4]
  [ 8  8  4  3  4]
  [ 2  2 10  8 10]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [58]:
# your code here

e = a * c
print(e)

[[[ 2  2  5  7  3]
  [ 5  1  3 10  5]
  [ 5  9  8  4  1]]

 [[ 8  4  0  6  3]
  [ 7  7  3  2  3]
  [ 1  1  9  7  9]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [0]:
# If we want to mulitply arrays we need to use the module .dot . Array multiplication is not matrix multiplication.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [59]:
# There are specific methods in Numpy to find max, min and mean of an array:

d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
 

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [61]:
# your code here

f = np.empty([2, 3, 5], dtype = float)


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [62]:
# your code here
for a in range(2):
    for b in range(3):
        for c in range(5):
            if d[a, b, c] > d_min and d[a, b, c] < d_mean:
                f[a, b, c] = 25
            elif d[a, b, c] < d_max and d[a, b, c] > d_mean:
                f[a, b, c] = 75
            elif d[a, b, c] == d_mean:
                f[a, b, c] = 50
            elif d[a, b, c] == d_min:
                f[a, b, c] = 0
            elif d[a, b, c] == d_max:
                f[a, b, c] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [63]:
# your code here
print(d)
print(f)

[[[ 3  3  6  8  4]
  [ 6  2  4 11  6]
  [ 6 10  9  5  2]]

 [[ 9  5  1  7  4]
  [ 8  8  4  3  4]
  [ 2  2 10  8 10]]]
[[[ 25.  25.  75.  75.  25.]
  [ 75.  25.  25. 100.  75.]
  [ 75.  75.  75.  25.  25.]]

 [[ 75.  25.   0.  75.  25.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [65]:
# your code here
f = f.astype(str)
for a in range(2):
    for b in range(3):
        for c in range(5):
            if d[a, b, c] > d_min and d[a, b, c] < d_mean:
                f[a, b, c] = 'B'
            elif d[a, b, c] < d_max and d[a, b, c] > d_mean:
                f[a, b, c] = 'D'
            elif d[a, b, c] == d_mean:
                f[a, b, c] = 'C'
            elif d[a, b, c] == d_min:
                f[a, b, c] = 'A'
            elif d[a, b, c] == d_max:
                f[a, b, c] = 'E'

In [66]:
print(f)

[[['B' 'B' 'D' 'D' 'B']
  ['D' 'B' 'B' 'E' 'D']
  ['D' 'D' 'D' 'B' 'B']]

 [['D' 'B' 'A' 'D' 'B']
  ['D' 'D' 'B' 'B' 'B']
  ['B' 'B' 'D' 'D' 'D']]]
